name: Deploy artifacts
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: cloning code
        uses: actions/checkout@v4
      - name: Install denedencies 
        run: npm ci
      - name: Lint code 
        run: npm run lint
      - name: Testing code
        run: npm run test 

  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.filename.outputs.file-name }}
    steps:
      - name: cloning code
        uses: actions/checkout@v4
      - name: Install denedencies 
        run: npm ci
      - name: Building code 
        run: npm run build
      - name: saving artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist
            package.json
      - name: fetching files name
        id: filename
        run: find dist/assets/*.js -type -f -execdir echo 'file-name={}' >> $GITHUB_OUPTPUT ';'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "Deploying......"
      - name: downloading artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      - name: checking files
        run: ls -R
      - name: displaying files name
        run: echo  "${{ needs.build.outputs.script-file }}"

